### PUT request for creating new (empty) entry
POST http://localhost:3001/api/subjects/
Content-Type: application/json

{
  
}

### Put request for updating existing entry
PUT http://localhost:3001/api/subjects/64da2054616e0fb5e08fd784
Content-Type: application/json


{
  "data": [
    {
      "rowNum": 1,
      "condition": "control",
      "stimulus": "1",
      "response": "1"
    },
    {
      "rowNum": 2,
      "condition": "control",
      "stimulus": "1",
      "response": "1"
    },
    {
      "rowNum": 3,
      "condition": "control",
      "stimulus": "1",
      "response": "0"
    }
  ]
}



### checking all the data
GET http://localhost:3001/api/subjects/

### checking single subject data
GET http://localhost:3001/api/subjects/64da18d0616e0fb5e08fd77e
